config/routes.rb
Rails.application.routes.draw do
  resources :applications, only: [:index, :show, :new, :create, :destroy] do
    resources :ftps_accounts, path: 'ftpsaccounts', only: [:index, :new, :create, :edit, :update, :destroy]
    resources :domains, only: [:index, :new, :create, :edit, :update, :destroy], constraints: {id: /[A-Za-z0-9\.\-\_]+/} do
      member do
        patch 'flags/enabled' => 'domains#update_enabled_flags', as: :update_enabled_flags
        patch 'flags/http' => 'domains#update_http_flags', as: :update_http_flags
        patch 'flags/https' => 'domains#update_https_flags', as: :update_https_flags
      end
    end
    resources :ssl_certificates, path: 'sslcertificates', only: [:index, :new, :create, :destroy]

    resources :databases, only: [:index, :new, :create, :destroy]
    resources :database_users, path: 'databaseusers', only: [:show, :edit, :update]

    resources :containers, only: [:index]
  end

  root 'applications#index'
  

end

app/models/domain.rb
require 'resolv'

class Domain < CaminoActiveRecord::Base
  belongs_to :application
  belongs_to :ssl_certificate
  
  validates :application,
            presence: true
  
  validates :name,
            uniqueness: {case_sensitive: false},
            presence: true,
            length: {in: 3..32},
            format: {with: /\A[A-Za-z0-9\.\-]*\z/}

  bitmask :flags, as: [:primary, :enabled, :http, :https]

  attr_readonly :name

  before_validation on: :create do
    self.name = self.name.downcase
  end
  
  validate do
    # TODO: add error messages for the case that the user tries to enable http or https while domain is disabled
    if self.ssl_certificate_id != nil and self.ssl_certificate_id_changed? and !self.application.ssl_certificates.include? self.ssl_certificate
      self.errors.add :ssl_certificate. I18t.t('activerecord.errors.messages.ssl_certificate_not_part_of_application')
    end
    
    if self.flags?(:primary)
      if !self.flags?(:enabled)
        self.errors.add :flags, I18n.t('activerecord.errors.messages.primary_cannot_be_disabled')
      end

      if !self.flags?(:http)
        self.errors.add :flags, I18n.t('activerecord.errors.messages.primary_http_cannot_be_disabled')
      end
    end
  end

  before_save do
    if !self.flags? :enabled
      self.flags.delete :http
      self.flags.delete :https
    end

    if !self.flags? :https
      self.ssl_certificate = nil
    end
  end

  before_destroy do
    if self.flags? :primary
      self.errors.add :flags, I18n.t('activerecord.errors.messages.primary_cannot_be_destroyed')
      false
    end
  end
  
  def to_param
    name
  end

  def http?
    self.flags?(:enabled, :http)
  end
  
  def https?
    self.flags?(:enabled, :https) && self.ssl_certificate
  end
  
  def addresses
    Resolv.getaddresses self.name
  end

  def whois
    Whois.whois(self.name)
  end

  def urls
    urls = []

    if self.flags? :http
      urls.push "http://#{self.name}"
    end
    if self.flags? :https
      urls.push "https://#{self.name}"
    end

    return urls
  end
end

app/controllers/domains_controller.rb
# coding: utf-8
class DomainsController < ApplicationController
  before_action :require_application
  before_action :require_domain, only: [:show, :destroy, :edit, :update]
  
  def index
    @domains = Domain.where application_id: @application.id
  end

  def new
  end

  def show
  end

  def edit
  end
  
  def update
    if params.include? :flags and params.permit(flags: ['enable', 'http', 'https'])
      @domain.flags.toggle(params[:flags])
      if !@domain.save
        @alerts = @domain.errors
      else
        @alerts = {t('entity_update_successfull', entity: Domain.model_name.human) => :success}
      end
    elsif params.require(:domain).permit(:ssl_certificate)
      @domain.ssl_certificate = @application.ssl_certificates.find_by_name params[:domain][:ssl_certificate]

      if !@domain.save!
        @alerts = @domain.errors
      else
        @alerts = {t('entity_update_successfull', entity: Domain.model_name.human) => :success}  
        params.clear
      end
    end

    render 'edit'
  end
  
  def create
    @domain = Domain.new params.require(:domain).permit(:name).merge(application_id: @application.id)
                                                                     
    if @domain.save
      @alerts = {t('entity_creation_successfull', entity: Domain.model_name.human) => :success}
      index
      render 'index'
    else
      @alerts = @domain.errors
      render 'new'
    end
  end

  def destroy
    if @domain.destroy
      @alerts = {t('entity_deletion_successfull', entity: Domain.model_name.human) => :success}
    else
      @alerts = {@domain.errors[:flags][0] => :danger}
    end

    index
    render 'index'
  end
end

app/views/domains/edit.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: t('edit_entity', entity: Domain.model_name.human), buttons: [{title: t('back'), href: application_domains_path, class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = render partial: 'others/alerts', locals: {alerts: @alerts}
  
  .card
    .card-header
      = @domain.name

      - if !@domain.flags? :primary
        .float-xs-right
          - if @domain.flags? :enabled
            = link_to t('disable'), application_domain_path(@application, @domain, flags: :enabled), method: :patch, class: 'btn btn-sm btn-secondary'
          - else
            = link_to t('enable'), application_domain_path(@application, @domain, flags: :enabled), method: :patch, class: 'btn btn-sm btn-primary'
        
    - if @domain.flags? :enabled
      .card-block
        - if !@domain.flags? :primary
          .card
            .card-header
              = t 'http'

              .float-xs-right
                - if @domain.flags? :http
                  = link_to t('disable'), application_domain_path(@application, @domain, flags: :http), method: :patch, class: 'btn btn-sm btn-secondary'
                - else
                  = link_to t('enable'), application_domain_path(@application, @domain, flags: :http), method: :patch, class: 'btn btn-sm btn-primary'

        .card
          .card-header
            = t 'https'

            .float-xs-right
              - if @domain.flags? :https
                = link_to t('disable'), application_domain_path(@application, @domain, flags: :https), method: :patch, class: 'btn btn-sm btn-secondary'
              - else
                = link_to t('enable'), application_domain_path(@application, @domain, flags: :https), method: :patch, class: 'btn btn-sm btn-primary'

          - if @domain.flags? :https
            .card-block
              - if @application.ssl_certificates.empty?
                .alert.alert-danger.mb-0
                  = t '.no_ssl_certificates_html', {ssl_certificates: SslCertificate.model_name.human(count: 2), href: link_to(t('create_entity', entity: SslCertificate.model_name.human), new_application_ssl_certificate_path)}
              - else
                = form_for :domain, url: application_domain_path(@application, @domain), method: :patch, html: {class: ''} do |f|
                  = validation_for 'form-group', :ssl_certificate, params[f.object_name.to_sym], @errors do
                    = f.label :ssl_certificate, SslCertificate.model_name.human, {class: 'form-control-label'}
                    = f.select :ssl_certificate, options_for_select([''] + @application.ssl_certificates.map{|i| i.name}, selected: @domain.ssl_certificate == nil ? '' : @domain.ssl_certificate.name), {}, {class: form_control_for(:ssl_certificate, params[f.object_name.to_sym], @errors)}

                  = f.submit t('save'), class: 'form-control btn btn-primary'

= render partial: 'layouts/content_wrapper'

app/views/domains/index.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: Domain.model_name.human(count: 2), buttons: [{title: t('create'), href: new_application_domain_path, class: 'btn-primary'}, {title: t('back'), href: application_path(@application), class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = render partial: 'others/alerts', locals: {alerts: @alerts}

  - @domains.each do |domain|
    .card
      .card-header
        = domain.name
        
        %span.btn-group.btn-group-sm.float-xs-right
          = link_to t('edit'), edit_application_domain_path(@application, domain), class: 'btn btn-warning'
          
          - if !domain.flags? :primary
            = link_to t('delete'), application_domain_path(@application, domain), method: :delete, class: 'btn btn-danger'

= render partial: 'layouts/content_wrapper'

app/views/domains/new.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: t('create_entity', entity: Domain.model_name.human), buttons: [{title: t('back'), href: application_domains_path, class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = form_for :domain, url: application_domains_path do |f|
    = validation_for 'form-group', :name, params[f.object_name.to_sym], @errors do
      = f.label :name, Domain.human_attribute_name(:name), {class: 'form-control-label'}
      = f.text_field :name, class: form_control_for(:name, params[f.object_name.to_sym], @errors), value: value_for(:name, f)

    = f.submit t('create'), class: 'form-control btn btn-primary'

= render partial: 'layouts/content_wrapper'