config/routes.rb
Rails.application.routes.draw do
  resources :applications, only: [:index, :show, :new, :create, :destroy] do
    resources :ftps_accounts, path: 'ftpsaccounts', only: [:index, :new, :create, :edit, :update, :destroy]
    resources :domains, only: [:index, :new, :create, :edit, :update, :destroy], constraints: {id: /[A-Za-z0-9\.\-\_]+/} do
      member do
        patch 'flags/enabled' => 'domains#update_enabled_flags', as: :update_enabled_flags
        patch 'flags/http' => 'domains#update_http_flags', as: :update_http_flags
        patch 'flags/https' => 'domains#update_https_flags', as: :update_https_flags
      end
    end
    resources :ssl_certificates, path: 'sslcertificates', only: [:index, :new, :create, :destroy]

    resources :databases, only: [:index, :new, :create, :destroy]
    resources :database_users, path: 'databaseusers', only: [:show, :edit, :update]

    resources :containers, only: [:index]
  end

  root 'applications#index'
  

end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  before_action :require_application
  before_action :require_database, only: [:destroy]
  
  def index
    @databases = Database.where database_user_id: @application.database_user.id
  end

  def new
  end
  
  def create
    @database = Database.new params.require(:database).permit(:name).merge(database_user_id: @application.database_user.id)
                                                                     
    if @database.save
      @alerts = {t('entity_creation_successfull', entity: Database.model_name.human) => :success}
      index
      render 'index'
    else
      @errors = @database.errors
      render 'new'
    end
  end

  def destroy
    @database.destroy

    @alerts = {t('entity_deletion_successfull', entity: Database.model_name.human) => :success}
    index
    render 'index'
  end
end

app/views/databases/index.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: Database.model_name.human(count: 2), buttons: [{title: t('create'), href: new_application_database_path, class: 'btn-primary'}, {title: t('back'), href: application_path(@application), class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = render partial: 'others/alerts', locals: {alerts: @alerts}

  - @databases.each do |database|
    .card
      .card-header
        = database.name
        
        %span.btn-group.btn-group-sm.float-xs-right
          = link_to t('delete'), application_database_path(@application, database), method: :delete, class: 'btn btn-danger'
          
= render partial: 'layouts/content_wrapper'

app/views/databases/new.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: t('create_entity', entity: Database.model_name.human), buttons: [{title: t('back'), href: application_databases_path, class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = form_for :database, url: application_databases_path do |f|
    = validation_for 'form-group', :name, params[f.object_name.to_sym], @errors do
      = f.label :name, Database.human_attribute_name(:name), {class: 'form-control-label'}
      .input-group
        .input-group-addon
          = @application.prefix('_', true)
        = f.text_field :name, class: form_control_for(:name, params[f.object_name.to_sym], @errors), value: value_for(:name, f)
            
    = f.submit t('create'), class: 'form-control btn btn-primary'
    
= render partial: 'layouts/content_wrapper'