config/routes.rb
Rails.application.routes.draw do
  resources :applications, only: [:index, :show, :new, :create, :destroy] do
    resources :ftps_accounts, path: 'ftpsaccounts', only: [:index, :new, :create, :edit, :update, :destroy]
    resources :domains, only: [:index, :new, :create, :edit, :update, :destroy], constraints: {id: /[A-Za-z0-9\.\-\_]+/} do
      member do
        patch 'flags/enabled' => 'domains#update_enabled_flags', as: :update_enabled_flags
        patch 'flags/http' => 'domains#update_http_flags', as: :update_http_flags
        patch 'flags/https' => 'domains#update_https_flags', as: :update_https_flags
      end
    end
    resources :ssl_certificates, path: 'sslcertificates', only: [:index, :new, :create, :destroy]

    resources :databases, only: [:index, :new, :create, :destroy]
    resources :database_users, path: 'databaseusers', only: [:show, :edit, :update]

    resources :containers, only: [:index]
  end

  root 'applications#index'
  

end

app/models/ftps_account.rb
require 'unix_crypt'

class FtpsAccount < CaminoActiveRecord::Base
  belongs_to :application
  has_many :ftps_account_logins, dependent: :destroy
  
  validates :application,
            presence: true
  
  validates :username,
            uniqueness: true,
            presence: true,
            length: {in: 3..32},
            format: {with: /\A[A-Za-z0-9\_\-]*\z/}

  validates :password,
            presence: {on: :create},
            confirmation: true,
            length: {minimum: 4, allow_nil: true}
  
  validates :password_confirmation,
            presence: true, if: '!password.nil?'

  attr_accessor :password, :password_confirmation

  attr_readonly :username
  
  before_validation on: :create do
    self.username = "#{self.application.name}_#{self.username}"
  end
  
  before_create do
    self.home_directory = self.application.ftps_path
  end
  
  before_save do
    if self.password.present?
      self.password_hash = UnixCrypt::DES.build password 
      
      self.password = self.password_confirmation = nil
    end
  end
  
  def to_param
    username
  end
end

app/controllers/ftps_accounts_controller.rb
class FtpsAccountsController < ApplicationController
  before_action :require_application
  before_action :require_ftps_account, only: [:edit, :update, :destroy]
  
  def index
    @ftps_accounts = FtpsAccount.where application_id: @application.id
  end

  def new
  end
  
  def create
    @ftps_account = FtpsAccount.new params.require(:ftps_account).permit(:username, :password, :password_confirmation).merge(application_id: @application.id)

    if @ftps_account.save
      @alerts = {t('entity_creation_successfull', entity: FtpsAccount.model_name.human) => :success}
      index
      render 'index'
    else
      @errors = @ftps_account.errors
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ftps_account.update_attributes params.require(:ftps_account).permit(:password, :password_confirmation)
      @alerts = {t('entity_update_successfull', entity: FtpsAccount.model_name.human) => :success}
      index
      render 'index'
    else
      @errors = @ftps_account.errors
      render 'edit'
    end
  end
  
  def destroy
    @ftps_account.destroy

    @alerts = {t('entity_deletion_successfull', entity: FtpsAccount.model_name.human) => :success}
    index
    render 'index'
  end
end

app/helpers/ftps_account_helper.rb
module FtpsAccountHelper
  def last_login ftps_account
    last = ftps_account.ftps_account_logins.last
    return I18n.l(last.created_at) unless last.nil?
    t('never')
  end
end

app/views/ftps_accounts/edit.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: t('edit_entity', entity: FtpsAccount.model_name.human), buttons: [{title: t('back'), href: application_ftps_accounts_path, class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  .card
    .card-header
      = @ftps_account.username
    .card-block
      = form_for :ftps_account, url: application_ftps_account_path(@application, @ftps_account), method: :patch do |f|
        = validation_for 'form-group', :password, params[f.object_name.to_sym], @errors do
          = f.label :password, FtpsAccount.human_attribute_name(:password), {class: 'form-control-label'}
          = f.password_field :password, class: form_control_for(:password, params[f.object_name.to_sym], @errors), value: value_for(:password, f)

        = validation_for 'form-group', :password_confirmation, params[f.object_name.to_sym], @errors do
          = f.label :password_confirmation, FtpsAccount.human_attribute_name(:password_confirmation), {class: 'form-control-label'}
          = f.password_field :password_confirmation, class: form_control_for(:password_confirmation, params[f.object_name.to_sym], @errors), value: value_for(:password_confirmation, f)

        = f.submit t('save'), class: ['form-control', 'btn', 'btn-primary']

= render partial: 'layouts/content_wrapper'

app/views/ftps_accounts/index.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: FtpsAccount.model_name.human(count: 2), buttons: [{title: t('create'), href: new_application_ftps_account_path, class: 'btn-primary'}, {title: t('back'), href: application_path(@application), class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = render partial: 'others/alerts', locals: {alerts: @alerts}

  - @ftps_accounts.each do |ftps_account|
    .card
      .card-header
        = ftps_account.username
      
        %span.btn-group.btn-group-sm.float-xs-right
          = link_to t('edit'), edit_application_ftps_account_path(@application, ftps_account), class: ['btn', 'btn-warning']
          = link_to t('delete'), application_ftps_account_path(@application, ftps_account), method: :delete, class: ['btn', 'btn-danger']

= render partial: 'layouts/content_wrapper'

app/views/ftps_accounts/new.html.haml
= render partial: 'layouts/header_wrapper', locals: {title: t('create_entity', entity: FtpsAccount.model_name.human), buttons: [{title: t('back'), href: application_ftps_accounts_path, class: 'btn-secondary'}]}
        
- content_for :content_wrapper_content do
  = form_for :ftps_account, url: application_ftps_accounts_path do |f|
    = validation_for 'form-group', :username, params[f.object_name.to_sym], @errors do
      = f.label :username, FtpsAccount.human_attribute_name(:username), {class: 'form-control-label'}
      .input-group
        .input-group-addon
          = @application.prefix('_', true)
        = f.text_field :username, class: form_control_for(:username, params[f.object_name.to_sym], @errors), value: value_for(:username, f)

    = validation_for 'form-group', :password, params[f.object_name.to_sym], @errors do
      = f.label :password, FtpsAccount.human_attribute_name(:password), {class: 'form-control-label'}
      = f.password_field :password, class: form_control_for(:password, params[f.object_name.to_sym], @errors), value: value_for(:password, f)

    = validation_for 'form-group', :password_confirmation, params[f.object_name.to_sym], @errors do
      = f.label :password_confirmation, FtpsAccount.human_attribute_name(:password_confirmation), {class: 'form-control-label'}
      = f.password_field :password_confirmation, class: form_control_for(:password_confirmation, params[f.object_name.to_sym], @errors), value: value_for(:password_confirmation, f)

    = f.submit t('create'), class: ['form-control', 'btn', 'btn-primary']

= render partial: 'layouts/content_wrapper'