config/routes.rb
Rails.application.routes.draw do
  resources :applications, only: [:index, :show, :new, :create, :destroy] do
    resources :ftps_accounts, path: 'ftpsaccounts', only: [:index, :new, :create, :edit, :update, :destroy]
    resources :domains, only: [:index, :new, :create, :edit, :update, :destroy], constraints: {id: /[A-Za-z0-9\.\-\_]+/} do
      member do
        patch 'flags/enabled' => 'domains#update_enabled_flags', as: :update_enabled_flags
        patch 'flags/http' => 'domains#update_http_flags', as: :update_http_flags
        patch 'flags/https' => 'domains#update_https_flags', as: :update_https_flags
      end
    end
    resources :ssl_certificates, path: 'sslcertificates', only: [:index, :new, :create, :destroy]

    resources :databases, only: [:index, :new, :create, :destroy]
    resources :database_users, path: 'databaseusers', only: [:show, :edit, :update]

    resources :containers, only: [:index]
  end

  root 'applications#index'
  

end

app/views/layouts/_content.html.haml
= yield

app/views/layouts/_content_wrapper.html.haml
.container
  .row
    .col-xs-4
      %ul.list-group
        %li.list-group-item
          = link_to t('dashboard'), application_path(@application)
      %ul.list-group.mt-1
        %li.list-group-item
          = link_to FtpsAccount.model_name.human(count: 2), application_ftps_accounts_path(@application)
        %li.list-group-item
          = link_to Domain.model_name.human(count: 2), application_domains_path(@application)
        %li.list-group-item
          = link_to SslCertificate.model_name.human(count: 2), application_ssl_certificates_path(@application)
          
      %ul.list-group.mt-1
        %li.list-group-item
          = link_to DatabaseUser.model_name.human, application_database_user_path(@application, @application.database_user)
        %li.list-group-item
          = link_to Database.model_name.human(count: 2), application_databases_path(@application)
        %li.list-group-item
          = link_to 'PHPMyAdmin', '/phpmyadmin', target: '_blank'

      = yield :content_wrapper_menu
      -#%ul.list-group.mt-1
        %li.list-group-item
          = link_to t('.applications'), '#'

        %li.list-group-item
          = link_to t('.file_browser'), '#'

    .col-xs-8
      = yield :content_wrapper_content

app/views/layouts/_header.html.haml
%nav.navbar.navbar-light.bg-faded
  .container
    = link_to 'camino', '#', class: 'navbar-brand'

    %ul.nav.navbar-nav.float-xs-right
      %li.nav-item
        = link_to t('greeting', username: session_manager.account.username), '#', class: 'nav-link active'
      %li.nav-item
        = link_to t('sign_out'), 'https://account.juteel.com/signout', class: 'nav-link'

app/views/layouts/_header_wrapper.html.haml
.container.pt-1
  .row
    .col-xs-8
      %h2
        = title
    .col-xs-4
      .btn-group.float-xs-right
        - buttons.each do |button|
          = link_to button[:title], button[:href], class: ['btn', button[:class]]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>camino</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/content' %>
    <%= render 'layouts/footer' %>
  </body>
</html>